FROM debian
RUN apt-get update && \
    apt-get upgrade -y && \
    apt-get install -y curl dnsutils gzip software-properties-common tar && \
    rm -rf /var/lib/apt/lists/*
RUN cd /usr/local && \
    curl --insecure -L -O https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.8%2B10/OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz && \
    tar xfvz OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz && \
    mv jdk-11.0.8+10 jdk && \
    rm OpenJDK11U-jdk_x64_linux_hotspot_11.0.8_10.tar.gz
ENV PATH=$PATH:/usr/local/jdk/bin
WORKDIR /mnt